name: 'EDW_data_pipeline'
version: '1.0.0'

profile: 'EDW_data_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  EDW_data_pipeline:
    staging:
      +schema: staging
      +materialized: table
      +warehouse: dbt_wh

    edw:
      +schema: edw
      +materialized: table
      +warehouse: dbt_wh

# Add this override:
dispatch:
  - macro_namespace: dbt
    search_order: ['EDW_data_pipeline', 'dbt']

# Prevent schema concatenation
quoting:
  schema: false